import { z } from "zod";

// Defines the structure for a single folio record.
export type Folio = {
  id: number;
  folio: string; // The unique, serialized folio number (e.g., DGIP-DAP-FIN-0001)
  section: string;
  addressee: string;
  subject: string;
  responsible: string;
  responsibleAvatarUrl: string;
  createdAt: Date;
  content: string; // The full folio text generated by AI
};

// Defines the structure for a section
export type Section = {
  id_seccion: number;
  nombre: string;
  codigo: string;
};

// Zod schema for validating the folio creation form.
// We use a function to create the schema dynamically based on the available sections.
export const createFolioFormSchema = (sections: [string, ...string[]]) => z.object({
  section: z.enum(sections, {
    required_error: "Debe seleccionar una sección.",
  }),
  addressee: z.string().min(3, "El destinatario debe tener al menos 3 caracteres."),
  subject: z.string().min(5, "El asunto debe tener al menos 5 caracteres."),
  responsible: z.string().min(3, "El responsable debe tener al menos 3 caracteres."),
  summary: z.string().min(10, "El resumen debe tener al menos 10 caracteres.").max(200, "El resumen no puede exceder los 200 caracteres."),
});

// TypeScript type inferred from the Zod schema for form values.
export type FolioFormValues = z.infer<ReturnType<typeof createFolioFormSchema>>;


// Zod schema for validating the login form.
export const loginFormSchema = z.object({
  email: z.string().email("Por favor, introduce un correo electrónico válido."),
  password: z.string().min(6, "La contraseña debe tener al menos 6 caracteres."),
});

// TypeScript type inferred from the Zod schema for login form values.
export type LoginFormValues = z.infer<typeof loginFormSchema>;
