import { z } from "zod";

// Defines the structure for a single folio record.
export type Folio = {
  id: string; // The unique, serialized folio number (e.g., DGIP-DAP-Finanzas-0001)
  section: string;
  addressee: string;
  subject: string;
  responsible: string;
  responsibleAvatarUrl: string;
  createdAt: Date;
  content: string; // The full folio text generated by AI
};

// Available sections for folio creation.
export const folioSections = [
  "Finanzas",
  "Recursos Humanos",
  "Tecnología",
  "Operaciones",
  "Legal",
] as const;

// Zod schema for validating the folio creation form.
export const folioFormSchema = z.object({
  section: z.enum(folioSections, {
    required_error: "Debe seleccionar una sección.",
  }),
  addressee: z.string().min(3, "El destinatario debe tener al menos 3 caracteres."),
  subject: z.string().min(5, "El asunto debe tener al menos 5 caracteres."),
  responsible: z.string().min(3, "El responsable debe tener al menos 3 caracteres."),
  summary: z.string().min(10, "El resumen debe tener al menos 10 caracteres.").max(200, "El resumen no puede exceder los 200 caracteres."),
});

// TypeScript type inferred from the Zod schema for form values.
export type FolioFormValues = z.infer<typeof folioFormSchema>;
