import { z } from "zod";

// Defines the structure for a single folio record.
export type Folio = { //Este folio es para los oficios
  id: number;
  folio: string; // The unique, serialized folio number (e.g., DGIP-DAP-FIN-0001)
  seccion: string;
  dirigido: string;
  asunto: string;
  tipo_asunto?:  string;
  responsable: number;
  nombre_responsable: string;
  responsibleAvatarUrl: string;
  fecha: Date;
  content: string; // The full folio text generated by AI
  archivo?: string; // Url del archivo 
};

export type Minuta = {
  id: number;
  folio: string;
  motivo: string;
  fecha_reunion: Date;
  convoca: string;
  acuerdos?: Array<{
    id: number;
    minuta_id: number;
    description: string;
    responsable: string;
  }>;
  responsable_acuerdo?: string;
  estado?: string;
  observaciones?: string;
  fecha_cumplimiento?: Date;
  evidencia?: string;
  createdAt: Date;
}

export type Acuerdo = {
  id: number;
  minuta_id: number;
  description: string;
  responsable?: string;
  fecha_compromiso: Date;
  fecha_cumplimiento?: Date; 
  observaciones?: string;
  estado?: string;
};

// Defines the structure for a section
export type Section = {
  id_seccion: number;
  nombre: string;
  codigo: string;
};

//Defines the structure for a user
export type Users = {
  id: number;
  id_uaa: number;
  name: string;
  email: string;
  seccion: string;
};

// Zod schema for validating the folio creation form.
// We use a function to create the schema dynamically based on the available sections.
export const createFolioFormSchema = (sections: string[]) => z.object({
  section: z.string().min(1, "Por favor seleccione una sección"),
  addressee: z.string().min(3, "El destinatario debe tener al menos 3 caracteres."),
  subjectType: z.enum(["Solicitar", "Informar"], {
    required_error: "Seleccione un tipo de asunto",
  }),
  subject: z.string().min(5, "El asunto debe tener al menos 5 caracteres."),
  responsible: z.string().min(1, "El responsable es obligatorio."),
  summary: z.string().optional(),//.min(10, "El resumen debe tener al menos 10 caracteres.").max(200, "El resumen no puede exceder los 200 caracteres."),
});

// TypeScript type inferred from the Zod schema for form values.
export type FolioFormValues = z.infer<ReturnType<typeof createFolioFormSchema>>;


// Zod schema for validating the login form.
export const loginFormSchema = z.object({
  email: z.string().email("Por favor, introduce un correo electrónico válido."),
  password: z.string().min(6, "La contraseña debe tener al menos 6 caracteres."),
});

export interface MinutaFormValues {
  motivo: string;
  fecha_reunion: string;
  convoca: string;
} 

export interface AcuerdoFornValues {
  description: string;
  responsable: string;
  fecha_comprimiso: string;
}

// TypeScript type inferred from the Zod schema for login form values.
export type LoginFormValues = z.infer<typeof loginFormSchema>;
